version: "3.3"

services:
    backend:
        image: ghcr.io/christianwaldmann/bookmarks-backend:v0.0.6
        environment:
            - PORT=8000
            - DATABASE_URL=sqlite:///database/db.sqlite3
            - BOOKMARKS_SECRET_KEY=change-me-in-production-use-a-random-string
            - BOOKMARKS_BACKEND_DOMAIN=localhost
            - BOOKMARKS_FRONTEND_BASE_URL=http://localhost:3000
        volumes:
            - backend-data:/database
        ports:
            - "8000:80"

    frontend:
        build:
            context: .
        environment:
            - BOOKMARKS_BACKEND_BASE_URL=http://localhost:8000
            - BOOKMARKS_GITHUB_LINK=https://github.com/christianwaldmann?tab=repositories&q=bookmarks
            - BOOKMARKS_STATUS_LINK=https://status.christianw.de/status/bookmarks
            - BOOKMARKS_API_DOCS_LINK=https://api.bookmarks.christianw.de/v1/docs
            - BOOKMARKS_UMAMI_TRACKING_LINK=https://analytics.christianw.de/script.js
            - BOOKMARKS_UMAMI_TRACKING_CODE=db5949e1-a6a1-4a42-81fd-af15899398a1
        ports:
            - "3000:80"

volumes:
    backend-data:
