version: "3.3"

services:
    frontend:
        build:
            context: .
            args:
                - BOOKMARKS_BACKEND_BASE_URL=http://localhost:8000
        ports:
            - "3000:80"
